// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/info": {
            "get": {
                "description": "管理员信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "管理员信息",
                "operationId": "/admin/info",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminInfoOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/account/login": {
            "post": {
                "description": "管理员登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "管理员登陆",
                "operationId": "/account/login",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/logistics/product/{id}": {
            "get": {
                "description": "读取货物批次详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物流企业-Logistics"
                ],
                "summary": "读取货物批次详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "批次编号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.ProductInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/logistics/tracking/{id}": {
            "get": {
                "description": "读取物流详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物流企业-Logistics"
                ],
                "summary": "读取物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.LogisticsCombinedRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/logistics/update/{id}": {
            "post": {
                "description": "物流记录上链",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物流企业-Logistics"
                ],
                "summary": "物流记录上链",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateLogisticRecordInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "物流追踪ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/manufacturer/order": {
            "post": {
                "description": "新建订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "制造商-Manufacturer"
                ],
                "summary": "新建订单",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.OrderInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/manufacturer/order/{id}": {
            "get": {
                "description": "读取订单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "制造商-Manufacturer"
                ],
                "summary": "读取订单详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Collection名称",
                        "name": "collection",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.OrderInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/manufacturer/product": {
            "post": {
                "description": "商品信息上链",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "制造商-Manufacturer"
                ],
                "summary": "商品信息上链",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProductInfoInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/manufacturer/product/{id}": {
            "get": {
                "description": "读取货物批次详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "制造商-Manufacturer"
                ],
                "summary": "读取货物批次详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "批次编号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.ProductInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/manufacturer/send": {
            "post": {
                "description": "发货记录上链",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "制造商-Manufacturer"
                ],
                "summary": "发货记录上链",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateLogisticRecordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/manufacturer/tracking/{id}": {
            "get": {
                "description": "读取物流详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "制造商-Manufacturer"
                ],
                "summary": "读取物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.LogisticsRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/qrcode/default": {
            "get": {
                "description": "获取默认图像",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "二维码"
                ],
                "summary": "获取默认图像",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.QRCodeImagesURL"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/qrcode/order/{id}": {
            "get": {
                "description": "根据订单号获取全部二维码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "二维码"
                ],
                "summary": "获取二维码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Collection名称",
                        "name": "collection",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.QRCodeImagesURL"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/regulator/private/{id}": {
            "get": {
                "description": "读取物流详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "监管机构-Regulator"
                ],
                "summary": "读取物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.LogisticsCombinedRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/regulator/product/{id}": {
            "get": {
                "description": "读取货物批次详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "监管机构-Regulator"
                ],
                "summary": "读取货物批次详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "批次编号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.ProductInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/regulator/tracking/{id}": {
            "get": {
                "description": "读取物流详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "监管机构-Regulator"
                ],
                "summary": "读取物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.LogisticsRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer1/order/{id}": {
            "get": {
                "description": "读取订单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商1-Retailer1"
                ],
                "summary": "读取订单详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.OrderInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer1/product/{id}": {
            "get": {
                "description": "读取货物批次详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商1-Retailer1"
                ],
                "summary": "读取货物批次详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "批次编号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.ProductInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer1/sign/{id}": {
            "post": {
                "description": "签收货物",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商1-Retailer1"
                ],
                "summary": "签收货物",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateLogisticRecordInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "物流追踪ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer1/tracking/{id}": {
            "get": {
                "description": "读取物流详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商1-Retailer1"
                ],
                "summary": "读取物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.LogisticsRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer2/order/{id}": {
            "get": {
                "description": "读取订单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商2-Retailer2"
                ],
                "summary": "读取订单详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.OrderInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer2/product/{id}": {
            "get": {
                "description": "读取货物批次详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商2-Retailer2"
                ],
                "summary": "读取货物批次详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "批次编号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.ProductInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer2/sign/{id}": {
            "post": {
                "description": "签收货物",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商2-Retailer2"
                ],
                "summary": "签收货物",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateLogisticRecordInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "物流追踪ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/retailer2/tracking/{id}": {
            "get": {
                "description": "读取物流详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "零售商2-Retailer2"
                ],
                "summary": "读取物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.LogisticsRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dao.LogisticsCombinedRecord": {
            "type": "object",
            "properties": {
                "private": {
                    "$ref": "#/definitions/dao.PrivateLogisticsRecord"
                },
                "public": {
                    "$ref": "#/definitions/dao.LogisticsRecord"
                }
            }
        },
        "dao.LogisticsRecord": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dao.RecordSubItem"
                    }
                }
            }
        },
        "dao.OrderInfo": {
            "type": "object",
            "properties": {
                "batch_number": {
                    "description": "OrderNumber    string  ` + "`" + `json:\"order_number\"` + "`" + `",
                    "type": "string"
                },
                "client": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "sorter": {
                    "description": "分拣员",
                    "type": "string"
                },
                "tracking_number": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "dao.PrivateLogisticsRecord": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dao.PrivateSubItem"
                    }
                }
            }
        },
        "dao.PrivateSubItem": {
            "type": "object",
            "properties": {
                "operator": {
                    "type": "string"
                },
                "peer_id": {
                    "type": "string"
                },
                "record_time": {
                    "type": "string"
                }
            }
        },
        "dao.ProductInfo": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "last_modified": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                }
            }
        },
        "dao.RecordSubItem": {
            "type": "object",
            "properties": {
                "record_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.AdminInfoOutput": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                },
                "login_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.AdminLoginOutput": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "返回的Token",
                    "type": "string",
                    "example": "token"
                }
            }
        },
        "dto.OrderInput": {
            "type": "object",
            "properties": {
                "batch_number": {
                    "type": "string"
                },
                "collection": {
                    "type": "string"
                },
                "order_number": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "sorter": {
                    "description": "分拣员",
                    "type": "string"
                },
                "tracking_number": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "dto.ProductInfoInput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "batch_num": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                }
            }
        },
        "dto.QRCodeImagesURL": {
            "type": "object",
            "properties": {
                "query_logistics_record_url": {
                    "type": "string"
                },
                "query_prod_info_url": {
                    "type": "string"
                },
                "update_logistics_status_url": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateLogisticRecordInput": {
            "type": "object",
            "properties": {
                "operator": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tracking_num": {
                    "type": "string"
                }
            }
        },
        "middleware.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "errmsg": {
                    "type": "string"
                },
                "errno": {
                    "type": "integer"
                },
                "stack": {
                    "type": "object"
                },
                "trace_id": {
                    "type": "object"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
